### ISSUE TITLE
Problem in executing the dataset cell !! line( 31 -102)

### ISSUE THREAD

**Issue by rashmiraj137** [vavrines/KitML.jl#7]
why is the dataset cell gives this error ?

MethodError: no method matching kernel_mode(::Int64, ::Int64, ::Int64, ::Int64, ::Float64, ::Float64, ::Float64, ::Int64, ::Int64, ::Int64, ::Float64)
Closest candidates are:
  kernel_mode(::I, ::R, ::R, ::R, !Matched::R, !Matched::R, !Matched::R, ::I, ::I, ::I, !Matched::R; quad_num) where {I<:Integer, R<:Real} at /Users/rashmiraj/.julia/packages/KitBase/Bi5WX/src/Theory/theory_atom.jl:815

Stacktrace:
 [1] top-level scope at ./In[17]:22
 [2] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1091

**Comment by vavrines** [comment]
> MethodError: no method matching kernel_mode(::Int64, ::Int64, ::Int64, ::Int64, ::Float64, ::Float64, ::Float64, ::Int64, ::Int64, ::Int64, ::Float64)

The function expects a float arg but receives an integer.
Fixed it in https://github.com/vavrines/KitML.jl/commit/bbd32f1467262ec9b0b8a4c51ceb3afb78cc461e.
Give it a try on main branch :100:

**Comment by rashmiraj137** [comment]
Thank you. Now it works.
